### PR TITLE
Add Kibble architecture diagram

### PR DESCRIPTION
**Pull request by turbaszek**
Kibble is a small project but the architecture is quite non-trivial. Having a diagram showing overview of all components should help users understand how things work 😉

### CODE REVIEW

**Comment by michalslowikowski00** [comment]
How to check it?

**Comment by Humbedooh** [comment]
Try https://www.planttext.com/ etc :)

**Comment by turbaszek** [comment]
If you want to preview the png you can click "display the rich diff":
Screenshot 2020-10-12 at 09 59 28

**Comment by Humbedooh** [comment]
Just a small note, that this depicts the _default flow_. It is (in theory!) possible to use other brokers than directly from scanner to elasticsearch. In my head, I have an idea of the default changing to always going through the JSON API as a broker, thus becoming more database-agnostic.

**Pull request merged**
