### PR TITLE
Usage doc

### PR DESCRIPTION
**Pull request by amunz**
Began an initial usage document. Includes the Setting Up the Base, Setting Up the Organisation, and Adding Sources sections.

### CODE REVIEW

**Comment by amunz** [comment]
Referencing issue #10

**Comment by turbaszek** [comment]
@sharanf @amunz should we close this PR? I think the content from this PR is already present here https://apache-kibble.readthedocs.io/en/latest/setup.html#installing-the-server and here https://apache-kibble.readthedocs.io/en/latest/managing.html

**Comment by sharanf** [comment]
> @sharanf @amunz should we close this PR? I think the content from this PR is already present here https://apache-kibble.readthedocs.io/en/latest/setup.html#installing-the-server and here https://apache-kibble.readthedocs.io/en/latest/managing.html

@turbaszek yes I agree. All the key points from this PR have already been incorporated into the documentation.

**Review by sharanf — COMMENTED** [review]
Thanks for the contribution. Unfortunately we won't be merging this PR as the information has already been included in the Apache Kibble documentation.

**Comment by sharanf** [comment]
I am closing this PR as this information has already been included in the Kibble documentation.

**Pull request closed without merging**
