### PR TITLE
Add Black to pre-commit

### PR DESCRIPTION
**Pull request by michalslowikowski00**
Hi folks.
This commit will add Black to pre-commit. 
With Black we will keep our repository clean and beautifully formatted.
If you don't know Black -- please take a look [here](https://github.com/psf/black).

You can also install Black as a tool in your IDE (Pycharm for example).
[Black in Pycharm](https://black.readthedocs.io/en/stable/editor_integration.html#pycharm-intellij-idea)

### CODE REVIEW

**Comment by turbaszek** [comment]
@michalslowikowski00 we need to run `pre-commit run --all-files` otherwise CI will be sad :<

**Comment by turbaszek** [comment]
@michalslowikowski00 would you mind rebasing? I merged #61

**Comment by michalslowikowski00** [comment]
Rebased, waiting with merge for Tomek's PR [67](https://github.com/apache/kibble/pull/67)

**Comment by turbaszek** [comment]
@michalslowikowski00 some files seem to be not formatted yet

**Review by turbaszek — APPROVED** [review]
Love it! Having a nice formatted code out of the box is wonderful ❤️

**Pull request merged**
